# Generated by Django 5.2.10 on 2026-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_applied',
            field=models.BooleanField(default=False),
        ),
    ]
