# Generated by Django 5.2.10 on 2026-02-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_inventory_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
