# Generated by Django 3.1.14 on 2026-01-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('telegram_bot_token', models.CharField(max_length=255)),
                ('telegram_chat_id', models.CharField(max_length=255)),
            ],
        ),
    ]
