# Generated by Django 5.2.10 on 2026-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Telegram bot token for this tenant', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat id for this tenant', max_length=100),
        ),
    ]
